/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Cinturones.Asientos;
import Parabrisas.Palabrisas;
import SistemaCombustible.Combustible;
import SensorReveraYFreno.Sensores;
import java.awt.Color;
import SistemaEncendido.Motor;
import SistemaIluminaciones.Luces;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import static java.awt.image.ImageObserver.WIDTH;
import javax.swing.Timer;

/**
 *
 * @author duvan
 */
public final class FrmCarro extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmCarro.class.getName());

    Combustible Gasolina = new Combustible();
    Sensores FrenoMano = new Sensores();
    Motor motor = new Motor();
    Luces luces = new Luces();
    Asientos asiento = new Asientos();
    Palabrisas palabrisas = new Palabrisas(motor);

    private boolean SensorDelante;
    private boolean SensorDetras;
    private int cont;
    private int tiempo;

    private boolean esperar;
    private boolean puerta1Abierta = false;
    private boolean puerta2Abierta = false;
    private boolean puerta3Abierta = false;
    private boolean puerta4Abierta = false;

    /**
     * Creates new form FrmCarro
     */
    public FrmCarro() {
        initComponents();
        timer.start();
        Activo.start();
        
        NoGas.setVisible(false);

        Sensor.setVisible(false);

        luzBaja1.setVisible(false);
        luzBaja2.setVisible(false);
        luzAlta1.setVisible(false);
        luzAlta2.setVisible(false);
        luzIntermitente.setVisible(false);

    }

    public void ActivarSensor() {
        Sensor.setVisible(true);
    }

    public void DesactivarSensor() {
        Sensor.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        SeeVelocimetro = new javax.swing.JProgressBar();
        SeeRPM = new javax.swing.JProgressBar();
        Prueba = new javax.swing.JTextField();
        SeeGasolina = new javax.swing.JProgressBar();
        btnFrenoMano = new javax.swing.JButton();
        luzBaja2 = new javax.swing.JButton();
        luzBaja1 = new javax.swing.JButton();
        btnRecargar = new javax.swing.JButton();
        luzAlta2 = new javax.swing.JButton();
        luzAlta1 = new javax.swing.JButton();
        Sensor = new javax.swing.JTextField();
        btnEncenderApagar = new javax.swing.JButton();
        btnLuces = new javax.swing.JButton();
        btnPuerta1 = new javax.swing.JButton();
        btnPuerta2 = new javax.swing.JButton();
        btnPuerta3 = new javax.swing.JButton();
        btnPuerta4 = new javax.swing.JButton();
        luzPuertas = new javax.swing.JButton();
        btnLucesIntermitentes = new javax.swing.JButton();
        luzIntermitente = new javax.swing.JButton();
        NoGas = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        btnAcelerar = new javax.swing.JButton();
        btnFrenoDePieXD = new javax.swing.JButton();
        Numeracion = new javax.swing.JTextField();
        txtKilometraje = new javax.swing.JTextField();
        ImagenDetras = new javax.swing.JLabel();
        btnAbr4 = new javax.swing.JButton();
        btnDes4 = new javax.swing.JButton();
        btnDes = new javax.swing.JButton();
        btnAbr = new javax.swing.JButton();
        btnAbr2 = new javax.swing.JButton();
        btnDes2 = new javax.swing.JButton();
        btnDes3 = new javax.swing.JButton();
        btnAbr3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        PalaApagado = new javax.swing.JButton();
        PalaVelo1 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        PalaVelo2 = new javax.swing.JButton();
        PalaVelo3 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jpalabrisas = new javax.swing.JButton();
        ImagenDeFrente = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SeeVelocimetro.setBackground(new java.awt.Color(255, 255, 51));
        SeeVelocimetro.setOpaque(true);
        jPanel1.add(SeeVelocimetro, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 440, 320, 30));

        SeeRPM.setBackground(new java.awt.Color(255, 51, 0));
        SeeRPM.setMaximum(10);
        SeeRPM.setOrientation(1);
        SeeRPM.setOpaque(true);
        jPanel1.add(SeeRPM, new org.netbeans.lib.awtextra.AbsoluteConstraints(1470, 360, 40, 110));

        Prueba.setEditable(false);
        Prueba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PruebaActionPerformed(evt);
            }
        });
        jPanel1.add(Prueba, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 470, 60, 40));

        SeeGasolina.setBackground(new java.awt.Color(204, 204, 0));
        SeeGasolina.setForeground(new java.awt.Color(204, 204, 0));
        SeeGasolina.setOrientation(1);
        SeeGasolina.setOpaque(true);
        jPanel1.add(SeeGasolina, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 360, 60, 110));

        btnFrenoMano.setBackground(new java.awt.Color(0, 0, 0));
        btnFrenoMano.setForeground(new java.awt.Color(0, 255, 0));
        btnFrenoMano.setText("FrenoDeMano");
        btnFrenoMano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFrenoManoActionPerformed(evt);
            }
        });
        jPanel1.add(btnFrenoMano, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 910, 150, 20));

        luzBaja2.setBackground(new java.awt.Color(153, 153, 0));
        luzBaja2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                luzBaja2ActionPerformed(evt);
            }
        });
        jPanel1.add(luzBaja2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 560, 20, 20));

        luzBaja1.setBackground(new java.awt.Color(153, 153, 0));
        luzBaja1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                luzBaja1ActionPerformed(evt);
            }
        });
        jPanel1.add(luzBaja1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 560, 20, 20));

        btnRecargar.setText("Recargar Gasolina");
        btnRecargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecargarActionPerformed(evt);
            }
        });
        jPanel1.add(btnRecargar, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 300, -1, -1));

        luzAlta2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                luzAlta2ActionPerformed(evt);
            }
        });
        jPanel1.add(luzAlta2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 490, 90, 30));

        luzAlta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                luzAlta1ActionPerformed(evt);
            }
        });
        jPanel1.add(luzAlta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 490, 90, 30));

        Sensor.setEditable(false);
        Sensor.setBackground(new java.awt.Color(255, 0, 0));
        Sensor.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Sensor.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Sensor.setText("¡SENSOR O FRENO ACTIVADO!");
        jPanel1.add(Sensor, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 10, -1, 40));

        btnEncenderApagar.setText("Motor EncenderApagar");
        btnEncenderApagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEncenderApagarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEncenderApagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 10, -1, -1));

        btnLuces.setText("Luces bajas,altas");
        btnLuces.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLucesActionPerformed(evt);
            }
        });
        jPanel1.add(btnLuces, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 40, -1, -1));

        btnPuerta1.setText("Puerta1");
        btnPuerta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPuerta1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnPuerta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 710, -1, -1));

        btnPuerta2.setText("Puerta2");
        btnPuerta2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPuerta2ActionPerformed(evt);
            }
        });
        jPanel1.add(btnPuerta2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 710, -1, -1));

        btnPuerta3.setText("Puerta3");
        btnPuerta3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPuerta3ActionPerformed(evt);
            }
        });
        jPanel1.add(btnPuerta3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 710, -1, -1));

        btnPuerta4.setText("Puerta4");
        btnPuerta4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPuerta4ActionPerformed(evt);
            }
        });
        jPanel1.add(btnPuerta4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 710, -1, -1));

        luzPuertas.setBackground(new java.awt.Color(0, 0, 0));
        luzPuertas.setText("jButton5");
        luzPuertas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                luzPuertasActionPerformed(evt);
            }
        });
        jPanel1.add(luzPuertas, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 780, 100, 110));

        btnLucesIntermitentes.setText("Intermitentes");
        btnLucesIntermitentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLucesIntermitentesActionPerformed(evt);
            }
        });
        jPanel1.add(btnLucesIntermitentes, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 70, -1, -1));

        luzIntermitente.setBackground(new java.awt.Color(255, 102, 102));
        luzIntermitente.setText("luz de las intermitentes");
        jPanel1.add(luzIntermitente, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 110, -1, -1));

        NoGas.setText("Sin gasolina!");
        jPanel1.add(NoGas, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 10, -1, -1));

        jTextField1.setEditable(false);
        jTextField1.setText("Gasolina");
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 330, -1, -1));

        jTextField2.setEditable(false);
        jTextField2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.setText("Velocimetro");
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 390, 130, 40));

        jTextField3.setEditable(false);
        jTextField3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField3.setText("RPM");
        jPanel1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1460, 320, -1, -1));

        btnAcelerar.setText("Acelerar");
        jPanel1.add(btnAcelerar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 750, -1, -1));

        btnFrenoDePieXD.setText("Frenar/retroceder");
        jPanel1.add(btnFrenoDePieXD, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 750, -1, -1));

        Numeracion.setEditable(false);
        Numeracion.setBackground(new java.awt.Color(0, 0, 0));
        Numeracion.setText("0");
        jPanel1.add(Numeracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 340, -1, -1));

        txtKilometraje.setEditable(false);
        txtKilometraje.setText("Kilometraje");
        jPanel1.add(txtKilometraje, new org.netbeans.lib.awtextra.AbsoluteConstraints(1155, 310, 80, -1));

        ImagenDetras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Atras.jpg"))); // NOI18N
        ImagenDetras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ImagenDetrasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ImagenDetrasMouseExited(evt);
            }
        });
        jPanel1.add(ImagenDetras, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, -1, -1));

        btnAbr4.setBackground(new java.awt.Color(255, 0, 51));
        btnAbr4.setText("Abr4");
        btnAbr4.setOpaque(true);
        btnAbr4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbr4ActionPerformed(evt);
            }
        });
        jPanel1.add(btnAbr4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1400, 200, 60, -1));

        btnDes4.setText("Des4");
        btnDes4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDes4ActionPerformed(evt);
            }
        });
        jPanel1.add(btnDes4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1400, 150, 60, -1));

        btnDes.setText("Des1");
        btnDes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDesActionPerformed(evt);
            }
        });
        jPanel1.add(btnDes, new org.netbeans.lib.awtextra.AbsoluteConstraints(1400, 100, 60, -1));

        btnAbr.setBackground(new java.awt.Color(255, 0, 0));
        btnAbr.setText("Abr1");
        btnAbr.setOpaque(true);
        btnAbr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbrActionPerformed(evt);
            }
        });
        jPanel1.add(btnAbr, new org.netbeans.lib.awtextra.AbsoluteConstraints(1400, 40, -1, -1));

        btnAbr2.setBackground(new java.awt.Color(255, 0, 0));
        btnAbr2.setText("Abr2");
        btnAbr2.setOpaque(true);
        btnAbr2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbr2ActionPerformed(evt);
            }
        });
        jPanel1.add(btnAbr2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1290, 40, 60, -1));

        btnDes2.setText("Des2");
        btnDes2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDes2ActionPerformed(evt);
            }
        });
        jPanel1.add(btnDes2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1300, 100, 60, -1));

        btnDes3.setText("Des3");
        btnDes3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDes3ActionPerformed(evt);
            }
        });
        jPanel1.add(btnDes3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1300, 140, 60, -1));

        btnAbr3.setBackground(new java.awt.Color(255, 0, 51));
        btnAbr3.setText("Abr3");
        btnAbr3.setOpaque(true);
        btnAbr3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbr3ActionPerformed(evt);
            }
        });
        jPanel1.add(btnAbr3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1290, 200, 60, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/CarroDentro_1.jpg"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 280, 1030, -1));

        PalaApagado.setText("Apagado");
        PalaApagado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PalaApagadoActionPerformed(evt);
            }
        });
        jPanel1.add(PalaApagado, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 420, -1, -1));

        PalaVelo1.setText("Velocidad 1");
        PalaVelo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PalaVelo1ActionPerformed(evt);
            }
        });
        jPanel1.add(PalaVelo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 450, -1, -1));

        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1400, 0, 70, 30));

        PalaVelo2.setText("Velocidad 2");
        PalaVelo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PalaVelo2ActionPerformed(evt);
            }
        });
        jPanel1.add(PalaVelo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 480, -1, -1));

        PalaVelo3.setText("Velocidad 3");
        PalaVelo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PalaVelo3ActionPerformed(evt);
            }
        });
        jPanel1.add(PalaVelo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 510, -1, -1));
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1290, 3, -1, 30));

        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1410, 240, -1, 30));

        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 240, -1, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/SistemCinturonHori.jpg"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 10, -1, -1));

        jpalabrisas.setBackground(new java.awt.Color(204, 204, 204));
        jpalabrisas.setPreferredSize(new java.awt.Dimension(320, 75));
        jPanel1.add(jpalabrisas, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 360, 320, 10));

        ImagenDeFrente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/DeFrente.jpg"))); // NOI18N
        ImagenDeFrente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ImagenDeFrenteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ImagenDeFrenteMouseExited(evt);
            }
        });
        jPanel1.add(ImagenDeFrente, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 988, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRecargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecargarActionPerformed
        SeeGasolina.setValue(Gasolina.RecargarGasolina());
    }//GEN-LAST:event_btnRecargarActionPerformed

    Timer timer = new Timer(1000, new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
            if (motor.estaEncendido()) {
                Gasolina.GastarGasolina();
                SeeGasolina.setValue(Gasolina.ObtenerCantidad());
                Prueba.setText(String.valueOf(Gasolina.ObtenerCantidad()));
            }
            if (!motor.estaEncendido()) {
                luzBaja1.setVisible(false);
                luzBaja2.setVisible(false);
                luzAlta1.setVisible(false);
                luzAlta2.setVisible(false);
                cont = 0;
            }
            if (Gasolina.ObtenerCantidad() == 0) {
                timer.stop();
                espera.start();
                esperar = true;
                NoGas.setVisible(false);
            }
        }
    });
    Timer espera = new Timer(1000, new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
            if (Gasolina.ObtenerCantidad() != 0 && esperar) {
                timer.start();
                espera.stop();
                esperar = false;
                NoGas.setVisible(true);
            }
            if (!motor.estaEncendido()) {
                luzBaja1.setVisible(false);
                luzBaja2.setVisible(false);
                luzAlta1.setVisible(false);
                luzAlta2.setVisible(false);
                cont = 0;
            }
        }
    });


    private void ImagenDetrasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ImagenDetrasMouseEntered
        this.SensorDetras = true;
    }//GEN-LAST:event_ImagenDetrasMouseEntered

    private void ImagenDeFrenteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ImagenDeFrenteMouseEntered
        this.SensorDelante = true;
    }//GEN-LAST:event_ImagenDeFrenteMouseEntered

    private void btnFrenoManoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFrenoManoActionPerformed
        if (FrenoMano.isFrenoMano()) {
            FrenoMano.desactivarFreno();
            btnFrenoMano.setForeground(Color.RED);
        } else {
            FrenoMano.activarFreno();
            btnFrenoMano.setForeground(Color.GREEN);
        }
    }//GEN-LAST:event_btnFrenoManoActionPerformed

    private void ImagenDeFrenteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ImagenDeFrenteMouseExited
        this.SensorDelante = false;
    }//GEN-LAST:event_ImagenDeFrenteMouseExited

    private void ImagenDetrasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ImagenDetrasMouseExited
        this.SensorDetras = false;
    }//GEN-LAST:event_ImagenDetrasMouseExited
    Timer Activo = new Timer(500, new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
            if (FrenoMano.isFrenoMano() || SensorDetras || SensorDelante) {
                ActivarSensor();

            } else {
                DesactivarSensor();
            }
        }
    });
    private void btnEncenderApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEncenderApagarActionPerformed
        if (Gasolina.ObtenerCantidad() != 0) {
            if (motor.estaEncendido()) {
                motor.motorApagado();
                btnEncenderApagar.setForeground(Color.RED);
            } else {
                motor.motorEncendido();
                btnEncenderApagar.setForeground(Color.GREEN);
            }
        }
    }//GEN-LAST:event_btnEncenderApagarActionPerformed

    private void btnLucesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLucesActionPerformed
        if (motor.estaEncendido()) {
            cont++;
        }
        if (cont == 3 || cont == 0) {
            cont = 0;
            luces.luzApagadas();

            luzBaja1.setVisible(false);
            luzBaja2.setVisible(false);
            luzAlta1.setVisible(false);
            luzAlta2.setVisible(false);

        } else if (cont == 1 && motor.estaEncendido()) {
            luces.luzBajaEncendida();
            luzBaja1.setVisible(true);
            luzBaja2.setVisible(true);

        } else if (cont == 2 && motor.estaEncendido()) {
            luzBaja1.setVisible(false);
            luzBaja2.setVisible(false);

            luces.luzAltaEncendidas();
            luzAlta1.setVisible(true);
            luzAlta2.setVisible(true);
        }


    }//GEN-LAST:event_btnLucesActionPerformed

    private void luzBaja2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_luzBaja2ActionPerformed

    }//GEN-LAST:event_luzBaja2ActionPerformed

    private void luzBaja1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_luzBaja1ActionPerformed

    }//GEN-LAST:event_luzBaja1ActionPerformed

    private void luzAlta2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_luzAlta2ActionPerformed

    }//GEN-LAST:event_luzAlta2ActionPerformed

    private void btnPuerta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPuerta1ActionPerformed

    }//GEN-LAST:event_btnPuerta1ActionPerformed

// puertas

    private void luzPuertasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_luzPuertasActionPerformed
        if (puerta1Abierta || puerta2Abierta || puerta3Abierta || puerta4Abierta) {
            luzPuertas.setBackground(Color.BLACK);
        } else {
            luzPuertas.setBackground(Color.WHITE);
        }
    }//GEN-LAST:event_luzPuertasActionPerformed

    private void btnPuerta2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPuerta2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPuerta2ActionPerformed

    private void btnPuerta3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPuerta3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPuerta3ActionPerformed

    private void btnPuerta4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPuerta4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPuerta4ActionPerformed

    private void btnLucesIntermitentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLucesIntermitentesActionPerformed
        cont++;
        if (cont == 0) {
            cont = 0;

            luces.luzApagadas();
            luzIntermitente.setVisible(false);

        } else if (cont == 1 && motor.estaEncendido()) {
            luces.intermitentesEncendidas();
            luzIntermitente.setVisible(true);

        } else if (cont == 2 && motor.estaEncendido()) {
            luces.luzApagadas();
            luzIntermitente.setVisible(false);
        }
    }//GEN-LAST:event_btnLucesIntermitentesActionPerformed

    private void luzAlta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_luzAlta1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_luzAlta1ActionPerformed

    private void PruebaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PruebaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PruebaActionPerformed

    private void btnAbrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbrActionPerformed
        asiento.abrochar(asiento.getConductor());
        btnAbr.setBackground(Color.WHITE);
        btnDes.setBackground(Color.CYAN);
    }//GEN-LAST:event_btnAbrActionPerformed

    private void btnAbr2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbr2ActionPerformed
        asiento.abrochar(asiento.getCopiloto());
        btnAbr2.setBackground(Color.WHITE);
        btnDes2.setBackground(Color.CYAN);
    }//GEN-LAST:event_btnAbr2ActionPerformed

    private void btnAbr4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbr4ActionPerformed
        asiento.abrochar(asiento.getPasagero2());
        btnAbr4.setBackground(Color.WHITE);
        btnDes4.setBackground(Color.CYAN);
    }//GEN-LAST:event_btnAbr4ActionPerformed

    private void btnDesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDesActionPerformed
        asiento.desabrochar(asiento.getConductor());
        btnAbr.setBackground(Color.RED);
        btnDes.setBackground(Color.WHITE);
    }//GEN-LAST:event_btnDesActionPerformed

    private void btnDes2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDes2ActionPerformed
        asiento.desabrochar(asiento.getCopiloto());
        btnAbr2.setBackground(Color.RED);
        btnDes2.setBackground(Color.WHITE);
    }//GEN-LAST:event_btnDes2ActionPerformed

    private void btnDes3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDes3ActionPerformed
        asiento.desabrochar(asiento.getPasajero1());
        btnAbr3.setBackground(Color.RED);
        btnDes3.setBackground(Color.WHITE);
    }//GEN-LAST:event_btnDes3ActionPerformed

    private void btnDes4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDes4ActionPerformed
        asiento.desabrochar(asiento.getPasagero2());
        btnAbr4.setBackground(Color.RED);
        btnDes4.setBackground(Color.WHITE);
    }//GEN-LAST:event_btnDes4ActionPerformed

    private void btnAbr3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbr3ActionPerformed
        asiento.abrochar(asiento.getPasajero1());
        btnAbr3.setBackground(Color.WHITE);
        btnDes3.setBackground(Color.CYAN);
    }//GEN-LAST:event_btnAbr3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void PalaVelo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PalaVelo1ActionPerformed
        tiempo = 1000;
        PalaTimer.start();
    }//GEN-LAST:event_PalaVelo1ActionPerformed

    private void PalaApagadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PalaApagadoActionPerformed
        PalaTimer.stop();
        jpalabrisas.setSize(320, 10);
    }//GEN-LAST:event_PalaApagadoActionPerformed

    private void PalaVelo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PalaVelo2ActionPerformed
        tiempo = 750;
        PalaTimer.start();
    }//GEN-LAST:event_PalaVelo2ActionPerformed

    private void PalaVelo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PalaVelo3ActionPerformed
        tiempo = 500;
        PalaTimer.start();
    }//GEN-LAST:event_PalaVelo3ActionPerformed

    Timer PalaTimer = new Timer(tiempo, new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
            if (motor.estaEncendido()) {
                if (jpalabrisas.getHeight() == 10) {
                    jpalabrisas.setSize(320, 75);
                } else {
                    jpalabrisas.setSize(320, 10);
                }
            }

        }
    });
    // // // // // // // 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmCarro().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ImagenDeFrente;
    private javax.swing.JLabel ImagenDetras;
    private javax.swing.JTextField NoGas;
    private javax.swing.JTextField Numeracion;
    private javax.swing.JButton PalaApagado;
    private javax.swing.JButton PalaVelo1;
    private javax.swing.JButton PalaVelo2;
    private javax.swing.JButton PalaVelo3;
    private javax.swing.JTextField Prueba;
    private javax.swing.JProgressBar SeeGasolina;
    private javax.swing.JProgressBar SeeRPM;
    private javax.swing.JProgressBar SeeVelocimetro;
    private javax.swing.JTextField Sensor;
    private javax.swing.JButton btnAbr;
    private javax.swing.JButton btnAbr2;
    private javax.swing.JButton btnAbr3;
    private javax.swing.JButton btnAbr4;
    private javax.swing.JButton btnAcelerar;
    private javax.swing.JButton btnDes;
    private javax.swing.JButton btnDes2;
    private javax.swing.JButton btnDes3;
    private javax.swing.JButton btnDes4;
    private javax.swing.JButton btnEncenderApagar;
    private javax.swing.JButton btnFrenoDePieXD;
    private javax.swing.JButton btnFrenoMano;
    private javax.swing.JButton btnLuces;
    private javax.swing.JButton btnLucesIntermitentes;
    private javax.swing.JButton btnPuerta1;
    private javax.swing.JButton btnPuerta2;
    private javax.swing.JButton btnPuerta3;
    private javax.swing.JButton btnPuerta4;
    private javax.swing.JButton btnRecargar;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JButton jpalabrisas;
    private javax.swing.JButton luzAlta1;
    private javax.swing.JButton luzAlta2;
    private javax.swing.JButton luzBaja1;
    private javax.swing.JButton luzBaja2;
    private javax.swing.JButton luzIntermitente;
    private javax.swing.JButton luzPuertas;
    private javax.swing.JTextField txtKilometraje;
    // End of variables declaration//GEN-END:variables

}
